sudo: false

language: node_js

node_js:
  - 0.12

services:
  - mongodb
#  - docker

cache:
  directories:
    - node_modules

branches:
  only:
    - master

before_install:
  - "npm install -g grunt-cli"

#install:

after_install:
  - echo "testing"
