sudo: required

language: node_js

node_js:
  - 0.12

services:
  - mongodb

cache:
  directories:
    - node_modules

branches:
  only:
    - master

before_install:
  - "npm install -g grunt-cli"

install:

after_success:
  - echo "Build Success"

after_failure:
  - echo "Build Error!"
