sudo: required

language: node_js

node_js:
  - 0.12

services:
  - docker

cache:
  directories:
    - node_modules

branches:
  only:
    - master

before_install:
  - npm grunt-cli
  - npm test

install:
  - npm install

after_install:
  - echo "testing"
