sudo: required

language: node_js

node_js:
  - 0.12

services:
  - mongodb

cache:
  directories:
    - node_modules

branches:
  only:
    - master

before_install:
  - cat /etc/apt/sources.list
  - sudo add-apt-repository 'deb https://apt.dockerproject.org/repo ubuntu-precise main'
  - sudo apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
  - sudo apt-get update
  - sudo apt-get install -y docker-engine
  - sudo service docker start
  - npm install -g grunt-cli

install:

after_success:
  - echo "Build Success"
  - docker ps -a

after_failure:
  - echo "Build Error!"
  - docker ps -a
